_BASE_: "Base_det.yaml"

MODEL:
  WEIGHTS: "C:/Users/hanta/Documents/projects/Tread_Detect/models/res50_ctw_model_pretrain.pth"
  TRANSFORMER:
    VOC_SIZE: 96
    NUM_POINTS: 50
    LOSS:
        BEZIER_SAMPLE_POINTS: 50
        BEZIER_CLASS_WEIGHT: 1.0
        BEZIER_COORD_WEIGHT: 1.0
        POINT_CLASS_WEIGHT: 1.0
        POINT_COORD_WEIGHT: 0.5
        POINT_TEXT_WEIGHT: 0.5 #0.5
        BOUNDARY_WEIGHT: 0.25
        
INPUT:
  ROTATE: False
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1200

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 5e-5 # 5e-5
  LR_BACKBONE: 5e-6 # 5e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)
  MAX_ITER: 12000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/ctw1500/finetune_maxlen50_96voc"
